// packages/gitgraph-angular/projects/gitgraph-angular/src/lib/graph/arrow/arrow.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
} from "@angular/core";

import { Commit, Coordinate, GitgraphCore } from "gitgraph-core";
import { arrowSvgPath } from "gitgraph-core/lib/utils";

@Component({
  // tslint:disable-next-line:component-selector
  selector: "[gg-arrow]",
  templateUrl: "./arrow.component.html",
  styleUrls: ["./arrow.component.scss"],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArrowComponent implements OnInit {
  @Input() public commit: Commit;
  @Input() public parent: Commit;
  @Input() public reverseArrow: boolean;
  @Input() public color: string;
  @Input() public core: GitgraphCore;

  public path: string;

  public origin: Coordinate;
  constructor() {}

  public ngOnInit(): void {
    const commitRadius = this.commit.style.dot.size;

    // Starting point, relative to commit
    this.origin = {
      x: this.reverseArrow
        ? commitRadius + (this.parent.x - this.commit.x)
        : commitRadius,
      y: this.reverseArrow
        ? commitRadius + (this.parent.y - this.commit.y)
        : commitRadius,
    };

    this.path = arrowSvgPath(this.core, this.parent, this.commit);
  }
}

<svg:g [attr.transform]="'translate(' + origin.x + ',' + origin.y + ')'">
  <svg:path [attr.d]="path" [attr.fill]="color" />
</svg:g>

// packages/gitgraph-react/src/Arrow.tsx
import * as React from "react";
import { ReactSvgElement } from "./types";
import {
  GitgraphCore,
  Commit,
  arrowSvgPath,
} from "@gitgraph/core";

interface ArrowProps {
  commits: Array<Commit<ReactSvgElement>>;
  commit: Commit<ReactSvgElement>;
  gitgraph: GitgraphCore<ReactSvgElement>;
  parentHash: string;
  commitRadius: number;
}

export class Arrow extends React.Component<ArrowProps> {
  public render() {
    const parent = this.props.commits.find(({ hash }) => hash === this.props.parentHash);
    if (!parent) return null;

    // Starting point, relative to commit
    const origin = this.props.gitgraph.reverseArrow
      ? {
        x: this.props.commitRadius + (parent.x - this.props.commit.x),
        y: this.props.commitRadius + (parent.y - this.props.commit.y),
      }
      : { x: this.props.commitRadius, y: this.props.commitRadius };

    return (
      <g transform={`translate(${origin.x}, ${origin.y})`}>
        <path
          d={arrowSvgPath(this.props.gitgraph, parent, this.props.commit)}
          fill={this.props.gitgraph.template.arrow.color!}
        />
      </g>
    );
  }
}
